%% Forward Premium
% This code calculates the market-implied forward premium (FP) using forward
% and spot exchange rates (for short maturities) and cross-currency swaps
% (for longer maturities).
% Assumes that read_platform.m, read_usyc.m, read_currencies have already been run.
% m-files called: compute_fp_short.m, compute_fp_long.m, remove_NaNcols.m
%
% Pavel Solís (pavel.solis@gmail.com), March 2019
%% Construct the FP Database
% LCs  = ['BRL2'; curncs]';         % Two formulas for Brazil
hdr_fp  = {};                       % No row 1 with titles (i.e. ready to be appended)
data_fp = datenum(TT_daily.Date);   % data_fp = dates; % 'dates' generated by read_bloomberg.m

for k = 1:numel(curncs)             % curncs generated by read_currencies.m
    [FP,hdr1]  = compute_fp_short(curncs{k},header_daily,dataset_daily,curncs);
    [CCS,hdr2] = compute_fp_long(curncs{k},header_daily,dataset_daily);
    hdr_fp     = [hdr_fp; hdr1; hdr2];
    data_fp    = [data_fp, FP, CCS];
end

[data_fp,hdr_fp] = remove_NaNcols(hdr_fp,data_fp);

%% Report FP Tenors per Currency
tnrperLCfp = {};                    % Count only after remove_NaNcols.m is called
LC_once = unique(hdr_fp(:,1),'stable');
for k = LC_once'
    ntnrperLC  = sum(strcmp(hdr_fp(:,1),k));
    tnrperLCfp = [tnrperLCfp; k, 'Fwd Prm', ntnrperLC];
end

clear k FP CCS hdr1 hdr2 LC_once ntnrperLC