%% Plot Spreads
% This code plots cross-currency swaps as well as local and foreign currency
% credit spreads for different countries.
% Assumes that read_data.m has already been run so that 'header_daily' and 
% 'dataset_daily' are in the workspace.
% Calls to m-files: none
%
% Pavel Solís (pavel.solis@gmail.com), September 2018
%%
LCs    = sheets(3:end);                 % 'sheets' generated by read_tickers_v4.m

%% Spreads per maturity for each countries
types  = {'LCUS','LCCS','FCCS','RHO'};
year   = '5';
fltrTP = ismember(header_daily(:,2),types);   % To report the specific types
fltrYR = ismember(header_daily(:,5),year);    % To report a specific year
for k = 1:numel(LCs)
    fltrLC  = ismember(header_daily(:,1),LCs{k});
    fltr    = fltrLC & fltrTP & fltrYR; % Criteria to meet
    sprds   = dataset_daily(:,fltr);
    sprdsMA = movmean(sprds,10);        % To report results as in Du & Schreger (2016)
    labels  = header_daily(fltr,2);           % Types available for the currency
    figure
    plot(dates,sprdsMA)
    title(['Spreads for ' LCs{k}])
    legend(labels)
    datetick('x','yyyy')                % Annual ticks
end

%% Spreads per country across maturities
keydates = [733681; 735385; 736664];    % datenum for Sept2008, May2013, Nov2016

type   = 'LCCS'; %'LCUS','FCCS','RHO'
years  = {'1','5','10'};
fltrTP = ismember(header_daily(:,2),type);    % To report the specific types
fltrYR = ismember(header_daily(:,5),years);   % To report a specific year
for k = 1:numel(LCs)
    fltrLC  = ismember(header_daily(:,1),LCs{k});
    fltr    = fltrLC & fltrTP & fltrYR; % Criteria to meet
    if sum(fltr) > 0                         % Some countries don't have the specified type
        sprds   = dataset_daily(:,fltr);
        sprdsMA = movmean(sprds,10);
        labels  = header_daily(fltr,5);           % Tenors of the spreads
        figure
        p1 = plot(dates,sprdsMA);
        line(repmat(keydates,1,2),get(gca,'YLim'),'Color',[0 0 0]+0.65,'LineStyle','-.');
        legend(p1,labels,'Location','best','Orientation','horizontal')
        title([type ' for ' LCs{k}])
        datetick('x','yyyy')
        %save_figure(['risk_premia_' ctrsLC{k}],saveit)
    end
end

%% Spreads per maturity across countries

fltr    = fltrTP & ismember(header_daily(:,5),year);
sprds   = dataset_daily(:,fltr);                  % cols are random variables, rows are observations
sprdsMA = movmean(sprds,10);
labels  = header_daily(fltr,1);                   % country
figure
plot(dates,sprdsMA)
title([type ' for ' year ' years'])
legend(labels,'Location','best')
datetick('x','yyyy')
[sprds_cov,sprds_p] = corrcoef(sprds,'Rows','complete');  % omits all rows of sprds containing NaN values
% Seems that LC credit spreads are highly correlated across countries in the sample

clear k p1 type* year* LCs fltr* sprds* keydates labels
