%% Read U.S. Yield Curve Data from GSW
% This code reads the Nelson-Siegel-Svensson parameters for the U.S. yield
% curve from the database of Gürkaynak, Sack & Wright (2007).
% Assumes that read_platform.m has already been run.
% m-files called: construct_hdr.m
%
% Pavel Solís (pavel.solis@gmail.com), March 2019
%%
path        = pwd;
cd(fullfile(path,'..','..','Data','Raw'))               % Use platform-specific file separators
filename    = 'original_US_Yield_Curve_Data.xlsx';
param_names = {'BETA0','BETA1','BETA2','BETA3','TAU1','TAU2'};

% Data
opts = spreadsheetImportOptions;
opts.VariableNamesRange = 'CQ10';                       % Starting cell for variable names
opts.DataRange          = 'CQ11';                       % Starting cell for observations
opts.VariableNames      = param_names;
opts   = setvartype(opts,opts.VariableNames,{'double'});
T_usyc = readtable(filename,opts);                      % Read parameters

opts = spreadsheetImportOptions;
opts.DataRange          = 'A11';                        % Starting cell for dates
opts.VariableNames      = 'Date';
opts = setvartype(opts,opts.VariableNames,{'datetime'});
T_dates = readtable(filename,opts);                     % Read dates

TT_usyc = table2timetable([T_dates, T_usyc]);           % Convert table to a timetable
cd(path)

% Headers
H_usyc  = construct_hdr('USD','PARAMETER',param_names','USD N-S-S YIELD CURVE',NaN,' ','GSW');
TH_usyc = cell2table(H_usyc);
TH_usyc.Properties.VariableNames = TH_pltfm.Properties.VariableNames;

% Merge timetables and headers
TT_daily = synchronize(TT_pltfm,TT_usyc,'commonrange'); % Union over the intersection of time ranges
TH_daily = [TH_pltfm; TH_usyc];

clear path filename opts param_names T_* H_* *_pltfm *_usyc

%%

path = pwd;
cd(fullfile(path,'..','..','Data'))% Use platform-dependent file separators
filename = 'original_US_Yield_Curve_Data.xlsx';
[dataGSW,txt] = xlsread(filename); % dataGSW only has values, txt includes headers and dates
cd(path)

% Headers
tnrmax = 10;                                % Maximum tenor needed is 10yrs
tckrUS = txt(10,[2:(tnrmax+1) 95:end])';    % Line 10 in GSW has the 'tickers'
aux1   = 1:tnrmax;
aux2   = cellstr(num2str(aux1'));           % Cell with all the tenors as strings
old    = ' '; new = '';
tnr_usyc  = strrep(aux2(:),old,new);        % Remove spaces
name_usyc = strcat('USD ZERO-COUPON YIELD',{' '},tnr_usyc,' YR');
hdr_usyc1 = construct_hdr('USD','HC',tckrUS(1:tnrmax),name_usyc,tnr_usyc); % HC - hard currency
hdr_usyc2 = construct_hdr('USD','PARAMETER',tckrUS(tnrmax+1:end),'N-S-S ZERO CURVE','X');
hdr_usyc  = [hdr_usyc1;hdr_usyc2];

% Dates
txt(1:10,:) = []; txt(:,2:end) = [];        % Only keep the dates from txt
dates_usyc   = datenum(txt);                % Convert dates from char to datenum

% Data
dataGSW  = [dates_usyc, dataGSW];           % Append the variables to the dates
dataGSW  = dataGSW(:,[1:(tnrmax+1) 95:end]);% Keep yields up to tnrmax and parameters
[~,idx1] = sort(dates_usyc);                % Sort dates in ascending order
dataGSW  = dataGSW(idx1,:);                 % Reorder dataset from earliest to latest 

% Sample
date1st    = min(dates);                    % 'dates' generated by read_bloomberg.m
dateEnd    = max(dates);                    % Start and end dates relative to 'dates'
idx2       = (dataGSW(:,1) >= date1st) & (dataGSW(:,1) <= dateEnd); % Logical
dataGSW    = dataGSW(idx2,:);               % Limit the dataset to the sample dates
dates_usyc = dataGSW(:,1);

% Match number of rows to data_blp.m (assumes size(dates,1) >= size(dates_usyc,1))
nT = numel(dates);
[datesmiss,idx_miss] = setdiff(dates,dates_usyc); % Dates in 'dates' not in 'dates_usyc'
samedates = ~ismember(1:nT,idx_miss);             % Logical for same dates
data_usyc = nan(nT,size(dataGSW,2));              % Pre-allocate output
data_usyc(samedates,:) = dataGSW(:,:);            % Populate same dates with GSW data
data_usyc(idx_miss,1)  = datesmiss;               % Cols 2:end are left as NaNs

clear path aux* idx* old new datesmiss samedates name_usyc hdr_usyc1 hdr_usyc2 nT
clear date1st dateEnd filename dataGSW tckrUS tnrmax tnr_usyc dates_usyc txt

%% Sources
% Insert rows in a matrix
% https://www.mathworks.com/matlabcentral/answers/...
% 276861-how-can-i-insert-a-row-in-the-middle-of-a-matrix-vector
% Convert a vector of doubles into a cell of strings
% https://www.mathworks.com/matlabcentral/answers/...
% 286544-how-i-could-convert-matrix-double-to-cell-array-of-string
% Concatanate strings with cell arrays of strings
% https://www.mathworks.com/matlabcentral/answers/...
% 18322-append-string-to-each-element-in-string-cell-array
% https://www.mathworks.com/matlabcentral/answers/9285-strcat-including-space-i-e