function rp_plot(dataset_monthly,header_monthly,YCtype,ctrsNcods,yr_subplot,saveit)
% This function plots the risk premia of different countries together; uses
% the dataset generated by rp_estimation.m
% Calls to m-files: save_figure.m, pnum2cell.m
%
%     INPUTS
% dataset_monthly - matrix with monthly obs of N-S curves as rows, col1 has dates
% header_monthly  - cell with names for the columns of data_monthly
% YCtype          - char with the type of risk premia to plot (from risky or risk-free LC)
% ctrsNcods       - cell with countries (and their IMF codes) to plot
% yr_plot         - double with the maturity to show in subplots
% saveit          - double: 1 to save figures, 0 otherwise
% 
% Pavel Solís (pavel.solis@gmail.com), September 2018
%
%% Risk premia per maturity across countries
yr_str   = num2str(yr_subplot);
fltrRP   = ismember(header_monthly(:,1),[YCtype 'RP']) & ismember(header_monthly(:,3),yr_str);
rp       = struct('cty',{},'dates',{},'data',{});
IDs      = cell2mat(ctrsNcods(:,2));
ctrsLC   = ctrsNcods(:,1);
keydates = [733681; 733863; 735415; 736664];        % datenum for Sept2008, March 2009, June2013, Nov2016

% Save the country, dates and data for all countries in a structure
for k = 1:numel(IDs)
    id          = IDs(k);
    fltrCTY     = dataset_monthly(:,2) == id;
    rp(k).cty   = ctrsLC{k};
    rp(k).dates = dataset_monthly(fltrCTY,1);
    rp(k).data  = dataset_monthly(fltrCTY,fltrRP);
    if id == 542                                    % Only for plotting purposes because long history
       rp(k).dates = rp(k).dates(64:end);
       rp(k).data  = rp(k).data(64:end);
    elseif id == 566                                 % Initial data for PHP may have issues (2001)
       rp(k).dates = rp(k).dates(15:end);
       rp(k).data  = rp(k).data(15:end);
    end
end

% Order in which countries will appear in subplots
% g = [1 5 6; 2 8 9; 3 11 13; 7 10 15; 4 12 14];      % By region
g = [2 7 11; 3 14 9; 8 15 4; 10 1 13; 6 5 12];        % For 5 & 10 YR TP

for l = 1:2
    figure
    for m = 1:2
        if l == 1; k = m; else; k = m + 2; end
        subplot(2,1,m);
        p1 = plot(rp(g(k,1)).dates,rp(g(k,1)).data,rp(g(k,2)).dates,rp(g(k,2)).data,'-.',...
            rp(g(k,3)).dates,rp(g(k,3)).data,'--');
        labels = {rp(g(k,1)).cty, rp(g(k,2)).cty, rp(g(k,3)).cty};
        line(repmat(keydates,1,2),get(gca,'YLim'),'Color',[0 0 0]+0.65,'LineStyle','-.'); %Vertical line
        datetick('x','yy')
        line(xlim,[0,0],'Color',[0 0 0]+0.6);  % Horizontal line at the origin
        legend(p1,labels,'Location','best','Orientation','horizontal')
        ylabel('Percent')
    end
    
    % Title over a group of subplots
    ax = axes('Units','Normal','Position',[.075 .075 .85 .85],'Visible','off');
    set(get(ax,'Title'),'Visible','on')
    title([yr_str '-Year Term Premia'])
    save_figure(['rp_',yr_str,'yr_',num2str(l)],saveit)
end

% Countries not in subplot
figure
k = 5;
p1 = plot(rp(g(k,1)).dates,rp(g(k,1)).data,rp(g(k,2)).dates,rp(g(k,2)).data,'-.',...
     rp(g(k,3)).dates,rp(g(k,3)).data,'--');
labels = {rp(g(k,1)).cty, rp(g(k,2)).cty, rp(g(k,3)).cty};
line(repmat(keydates,1,2),get(gca,'YLim'),'Color',[0 0 0]+0.65,'LineStyle','-.'); % Vertical lines
datetick('x','yy')
line(xlim,[0,0],'Color',[0 0 0]+0.6);  % Horizontal line at the origin
legend(p1,labels,'Location','best','Orientation','horizontal')
ylabel('Percent')
title([yr_str '-Year Term Premia'])
save_figure(['rp_' yr_str 'yr_3'],saveit)

%% Risk premia per country across maturities (Term structure of risk premia)
years    = [1; 5; 10];                      % Maturities for RP term structure
tsmats   = pnum2cell(years);

for k = 1:numel(IDs)
    id      = IDs(k);
    fltrCTY = dataset_monthly(:,2) == id;
    fltrYRS = ismember(header_monthly(:,1),[YCtype 'RP']) & ismember(header_monthly(:,3),tsmats);
    figure
    p1      = plot(dataset_monthly(fltrCTY,1),dataset_monthly(fltrCTY,fltrYRS));
    labels  = strcat(tsmats,' Yr');
    
    line(repmat(keydates,1,2),get(gca,'YLim'),'Color',[0 0 0]+0.65,'LineStyle','-.'); % Vertical lines
    datetick('x','yy')
    line(xlim,[0,0],'Color',[0 0 0]+0.6);  % Horizontal line at the origin
    legend(p1,labels,'Location','best','Orientation','horizontal')
    ylabel('Percent')
    title([ctrsLC{k} ' Term Structure of Term Premia'])
    save_figure(['rp_ts_' ctrsLC{k}],saveit)
end

%% Sources
%
% Insert a title over a group of subplots
% https://www.mathworks.com/matlabcentral/answers/100459-how-can-i-insert-a-title-over-a-group-of-subplots