function [corrExp,corrTP] = compare_atsm_surveys(S,currEM,showfigs)
% Compare Results from ATSM vs Surveys
% This code compares the paths of the expected long-term (LT) policy rate
% and the term premium obtained with an affine term structure model to those
% obtained from surveys.
% 
%	INPUTS
% struct: S         - contains names of countries/currencies, codes and YC data
% char: currEM      - ISO currency codes of EM in the sample
% logical: showfigs - display figures of the comparison if true
% 
%	OUTPUT
% cell: corrExp - nominal and synthetic correl w/surveys of expected LT policy rate
% cell: corrTP  - nominal and synthetic correl w/term premium from surveys
%
%   ASSUMPTIONS
% S in input is generated by forecastLTcbpol.m
% m-files called: none
% 
% Pavel Solís (pavel.solis@gmail.com), May 2019
%%
tnr     = 10;                                                                   % Maturity for long-term
nEMs    = length(currEM);
corrExp = cell(nEMs,3);
corrTP  = cell(nEMs,3);

for k = 1:nEMs
    if ismember(S(k).iso,{'ILS','ZAR'})                                         % No survey data
        continue
    else
        % Extract information
        ylds_svy = S(k).srvyldsE;                                               % Survey expectations
        ylds_nom = S(k).nomdata;                                                % Nominal yields
        ylds_syn = S(k).syndata;                                                % Synthetic yields
        yldsPnom = S(k).nomyldsP;                                               % Nominal expected yields
        yldsPsyn = S(k).synyldsP;                                               % Synthetic expected yields
        tp_nom   = S(k).nomtp;                                                  % Nominal term premium
        tp_syn   = S(k).syntp;                                                  % Synthetic term premium
        
        % Use the specified tenor, remove header and transform to percentages
        ylds_nom = [ylds_nom(2:end,1) ylds_nom(2:end,ylds_nom(1,:) == tnr)*100];
        ylds_syn = [ylds_syn(2:end,1) ylds_syn(2:end,ylds_syn(1,:) == tnr)*100];
        yldsPnom = [yldsPnom(2:end,1) yldsPnom(2:end,yldsPnom(1,:) == tnr)*100];
        yldsPsyn = [yldsPsyn(2:end,1) yldsPsyn(2:end,yldsPsyn(1,:) == tnr)*100];
        tp_nom   = [tp_nom(3:end,1) tp_nom(3:end,tp_nom(1,:) == tnr)];
        tp_syn   = [tp_syn(3:end,1) tp_syn(3:end,tp_syn(1,:) == tnr)];
        
        % Calculate the semiannual term premium using surveys
        fltrSVYnom = ismembertol(ylds_svy(:,1),ylds_nom(:,1),4,'DataScale',1);  % Compare dates
        fltrSVYsyn = ismembertol(ylds_svy(:,1),ylds_syn(:,1),4,'DataScale',1);  % Allow for long weekends
        fltrNOMyld = ismembertol(ylds_nom(:,1),ylds_svy(:,1),4,'DataScale',1);  % (i.e. up to 4 days around date)
        fltrSYNyld = ismembertol(ylds_syn(:,1),ylds_svy(:,1),4,'DataScale',1);
        ylds_nom   = ylds_nom(fltrNOMyld,:);                                    % Same periodicity
        ylds_syn   = ylds_syn(fltrSYNyld,:);                                    % Same range of dates
        tpnomsvy   = ylds_nom(:,2) - ylds_svy(fltrSVYnom,2);
        tpsynsvy   = ylds_syn(:,2) - ylds_svy(fltrSVYsyn,2);
        tp_nom_svy = [ylds_nom(:,1) tpnomsvy];
        tp_syn_svy = [ylds_syn(:,1) tpsynsvy];
        
        % Use the semmiannual long-term expected policy rate
        fltrSVYnmP = ismembertol(ylds_svy(:,1),yldsPnom(:,1),4,'DataScale',1);  % Same periodicity
        fltrSVYsnP = ismembertol(ylds_svy(:,1),yldsPsyn(:,1),4,'DataScale',1);  % Same range of dates
        fltrNOMyP  = ismembertol(yldsPnom(:,1),ylds_svy(:,1),4,'DataScale',1);
        fltrSYNyP  = ismembertol(yldsPsyn(:,1),ylds_svy(:,1),4,'DataScale',1);
        yldsPnom   = yldsPnom(fltrNOMyP,:);
        yldsPsyn   = yldsPsyn(fltrSYNyP,:);
        
        % Use the semmiannual ATSM term premium [Check whether ylds_svy or  tp_nom_svy/tp_syn_svy]
        fltrSVYnTP = ismembertol(tp_nom_svy(:,1),tp_nom(:,1),4,'DataScale',1);  % Same periodicity
        fltrSVYsTP = ismembertol(tp_syn_svy(:,1),tp_syn(:,1),4,'DataScale',1);  % Same range of dates
        fltrNOMtp  = ismembertol(tp_nom(:,1),tp_nom_svy(:,1),4,'DataScale',1);
        fltrSYNtp  = ismembertol(tp_syn(:,1),tp_syn_svy(:,1),4,'DataScale',1);
        tp_nom     = tp_nom(fltrNOMtp,:);
        tp_syn     = tp_syn(fltrSYNtp,:);
        
        % Compare long-term expected policy rates
        corrExp{k,1} = S(k).iso;
        corrExp{k,2} = corr(yldsPnom(:,2),ylds_svy(fltrSVYnmP,2),'Rows','complete');
        corrExp{k,3} = corr(yldsPsyn(:,2),ylds_svy(fltrSVYsnP,2),'Rows','complete');
        
        if showfigs
            figure
            plot(yldsPnom(:,1),yldsPnom(:,2),yldsPsyn(:,1),yldsPsyn(:,2),ylds_svy(:,1),ylds_svy(:,2))
            title([S(k).iso ' Expected Long-Term Policy Rate'])
            legend('Nominal','Synthetic','Surveys'), ylabel('%'), datetick('x','YY')
        end
        
        % Compare term premia
        corrTP{k,1} = S(k).iso;
        corrTP{k,2} = corr(tp_nom(:,2),tp_nom_svy(fltrSVYnTP,2),'Rows','complete');
        corrTP{k,3} = corr(tp_syn(:,2),tp_syn_svy(fltrSVYsTP,2),'Rows','complete');
        
        if showfigs
            figure
            plot(tp_nom(:,1),tp_nom(:,2),tp_nom_svy(:,1),tp_nom_svy(:,2))
            title([S(k).iso ' Nominal Term Premium'])
            legend('ATSM','Surveys'), ylabel('%'), datetick('x','YY')
            
            figure
            plot(tp_syn(:,1),tp_syn(:,2),tp_syn_svy(:,1),tp_syn_svy(:,2))
            title([S(k).iso ' Synthetic Term Premium'])
            legend('ATSM','Surveys'), ylabel('%'), datetick('x','YY')
        end
    end
end

% mean(cell2mat(corrExp([1:4 6:14],2:3)))
% mean(cell2mat(corrTP([1:4 6:14],2:3)))